apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app-name: pod
spec:
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app-name: pod-1
spec:
  affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app-name
              operator: In
              values:
              - pod
          topologyKey: topology.kubernetes.io/zone
  containers:
    - name: with-pod-affinity
      image: registry.k8s.io/pause:3.8